[package]
name = "lance-compression-estimation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Probing and encoding-aware optimization estimates for Lance files"

[dependencies]
anyhow.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
lance.workspace = true
lance-core.workspace = true
lance-file.workspace = true
lance-io.workspace = true
serde.workspace = true
tempfile.workspace = true
async-trait.workspace = true
object_store.workspace = true
object_store_opendal.workspace = true
opendal.workspace = true
url.workspace = true

[dev-dependencies]
tokio.workspace = true
